### PR TITLE
chore(project): migrate to travis-ci.com

### PR DESCRIPTION
**Pull request by barmac**
This migrates repo to travis-ci.com.

### CODE REVIEW

**Comment by barmac** [comment]
I think we can disable travis for this repo as it's created in a way to never pass build.

**Comment by philippfromme** [comment]
Let remove the badge then.

**Comment by barmac** [comment]
> Let remove the badge then.

Why? Once you use the boilerplate for your extension, it will work.

**Comment by philippfromme** [comment]
> Why? Once you use the boilerplate for your extension, it will work.

Sorry, I misunderstood your comment. Yes, let's keep the badge and disable Travis for this repository.

**Review by philippfromme — APPROVED** [review]

**Comment by barmac** [comment]
> disable Travis for this repository.

Done.

**Pull request merged**
